version: '3.8'

services:

  mysql:

    image: mysql:8.0

    container_name: fleetcart-mysql

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fleetcart

    ports:

      - "3307:3306"

    volumes:

      - mysql_data:/var/lib/mysql


  fleetcart:

    build: .

    container_name: fleetcart-app

    restart: always

    ports:

      - "8083:8080"

    depends_on:

      - mysql


volumes:

  mysql_data: